list_bowlers = ['DL Chahar',
'SR Watson',
'Harbhajan Singh',
'RA Jadeja',
'MA Wood',
'Imran Tahir',
'DJ Bravo',
'MJ McClenaghan',
'Mustafizur Rahman',
'JJ Bumrah',
'HH Pandya',
'M Markande',
'R Ashwin',
'MM Sharma',
'Mujeeb Ur Rahman',
'AR Patel',
'AJ Tye',
'MP Stoinis',
'TA Boult',
'Mohammed Shami',
'A Mishra',
'CH Morris',
'DT Christian',
'R Tewatia',
'R Vinay Kumar',
'PP Chawla',
'Kuldeep Yadav',
'SP Narine',
'MG Johnson',
'AD Russell',
'N Rana',
'YS Chahal',
'CR Woakes',
'Washington Sundar',
'UT Yadav',
'K Khejroliya',
'B Kumar',
'B Stanlake',
'Shakib Al Hasan',
'S Kaul',
'Rashid Khan',
'DS Kulkarni',
'JD Unadkat',
'K Gowtham',
'B Laughlin',
'S Gopal',
'BA Stokes',
'DJM Short',
'SN Thakur',
'TK Curran',
'S Nadeem',
'Sandeep Sharma',
'PJ Sangwan',
'BCJ Cutting',
'KH Pandya',
'GJ Maxwell',
'A Dananjaya',
'Shivam Mavi',
'P Negi',
'BB Sran',
'Yuvraj Singh',
'V Shankar',
'Mohammed Siraj',
'CJ Anderson',
'CJ Jordan',
'DJ Hooda',
'STR Binny',
'KV Sharma',
'AS Rajpoot',
'HV Patel',
'JC Archer',
'Avesh Khan',
'LE Plunkett',
'Mohammad Nabi',
'Basil Thampi',
'MK Tiwary',
'IS Sodhi',
'MK Lomror',
'YK Pathan',
'TG Southee',
'M Ashwin',
'L Ngidi',
'KM Asif',
'JP Duminy',
'C de Grandhomme',
'DJ Willey',
'M Prasidh Krishna',
'Anureet Singh'
]

for bowler in list_bowlers:
    print("#{}".format(bowler))
    print()
    print("{}_bowl <- data_bowl[data_bowl$Bowling==".format(bowler)+""" "{}",] """.format(bowler))
    print("{}_bowl <- col_add({}_bowl,95)".format(bowler,bowler))
    print("plot_add({}_bowl)".format(bowler))
    print("Predict({}_bowl)".format(bowler))
    print("\n")




